<?php

return [
    'archetypes' => [
        'security_significance' => [
            'name' => 'The Reliable Executor',
            'desire' => 'Tim ini ingin menjadi organisasi yang diakui atas keandalannya dan kemampuannya menyelesaikan pekerjaan dengan standar tinggi.',
            'fear' => 'Membuat kesalahan fatal yang merusak reputasi, atau dianggap sebagai tim yang tidak bisa diandalkan.',
            'strengths' => 'Tim ini sangat terstruktur, memiliki standar kualitas yang tinggi, dan hampir tidak pernah gagal memenuhi janji operasional.',
            'blindSpot' => 'Tim rentan terjebak dalam micromanagement dan bisa menjadi sangat kaku saat berhadapan dengan tenggat waktu atau situasi tak terduga.',
            'keyQuestion' => 'Apakah tim ini menjaga kualitas karena komitmen pada hasil terbaik, atau karena takut dikritik jika terjadi kesalahan kecil?',
        ],
        'security_connection' => [
            'name' => 'The Loyal Guardian',
            'desire' => 'Tim ini ingin membangun lingkungan kerja yang stabil, harmonis, dan saling percaya satu sama lain.',
            'fear' => 'Perpecahan internal atau pergeseran kepemimpinan yang merusak rasa aman dan kedekatan antar anggota.',
            'strengths' => 'Tim memiliki loyalitas tinggi, saling mendukung di masa krisis, dan mempertahankan budaya kerja yang hangat dan aman secara psikologis.',
            'blindSpot' => 'Tim sering menghindari keputusan sulit atau enggan memberi masukan kritis karena takut merusak keharmonisan yang sudah ada.',
            'keyQuestion' => 'Apakah tim ini menjaga keharmonisan karena kedekatan yang sehat, atau karena menghindari konflik yang sebenarnya perlu dibahas?',
        ],
        'security_growth' => [
            'name' => 'The Pragmatic Builder',
            'desire' => 'Tim ini ingin terus berkembang dan berinovasi, tapi dengan fondasi sistem dan proses yang sangat kuat serta terukur.',
            'fear' => 'Kehilangan kendali operasional akibat perubahan yang terlalu cepat atau inovasi yang tidak matang.',
            'strengths' => 'Tim luar biasa dalam mengeksekusi inovasi secara sistematis; mereka tidak hanya punya ide, tapi tahu bagaimana menstandarisasi ide tersebut.',
            'blindSpot' => 'Tim butuh waktu lebih lama untuk merespons perubahan pasar karena terlalu sibuk merencanakan semua skenario risiko sebelum mengeksekusi ide baru.',
            'keyQuestion' => 'Apakah proses ketat yang dibangun tim ini bertujuan memuluskan jalan, atau diam-diam digunakan sebagai alasan menunda inovasi?',
        ],
        'security_contribution' => [
            'name' => 'The Responsible Steward',
            'desire' => 'Tim ini ingin membangun organisasi yang stabil agar dapat secara konsisten memberi manfaat bagi klien, rekan kerja, dan masyarakat.',
            'fear' => 'Gagal memenuhi tanggung jawab dan mengecewakan pihak-pihak yang bergantung pada tim ini.',
            'strengths' => 'Tim ini luar biasa andal, selalu menepati janji komitmen, dan bekerja demi dampak jangka panjang tanpa banyak pamer.',
            'blindSpot' => 'Tim rentan memikul beban yang bukan tanggung jawabnya; sulit menolak pekerjaan ekstra yang pada akhirnya bisa memicu kelelahan massal (burnout).',
            'keyQuestion' => 'Apakah tim ini menjaga semua tanggung jawab karena memang sehat, atau karena merasa semuanya akan runtuh jika bukan tim ini yang mengurusnya?',
        ],
        'significance_connection' => [
            'name' => 'The Influential Connector',
            'desire' => 'Tim ini ingin menjadi kelompok yang dihargai, dipercaya, dan memberi pengaruh positif secara luas di dalam maupun luar perusahaan.',
            'fear' => 'Dianggap tidak relevan, tertinggal, atau kehilangan jaringan kolaborasi yang selama ini menjadi sumber kekuatan tim.',
            'strengths' => 'Tim sangat pandai membaca dinamika organisasi, membangun kolaborasi yang tulus (bukan transaksional), dan mahir mengomunikasikan visi dengan kuat.',
            'blindSpot' => 'Kebanggaan tim kadang terlalu bergantung pada pengakuan pihak luar atau manajemen atas, sehingga sulit mengatakan "tidak" demi menjaga citra baik.',
            'keyQuestion' => 'Apakah tim ini berkolaborasi karena benar-benar sejalan dengan visi, atau karena butuh validasi dan pengakuan dari pihak eksternal?',
        ],
        'significance_growth' => [
            'name' => 'The Ambitious Innovator',
            'desire' => 'Tim ini ingin terus berinovasi dan mencapai target-target luar biasa yang membuat mereka menonjol sebagai tim papan atas.',
            'fear' => 'Menjadi tim yang biasa-biasa saja (medioker) atau gagal mengoptimalkan potensi besar yang mereka miliki.',
            'strengths' => 'Tim sangat lincah belajar hal baru, memiliki visi progresif, dan secara kolektif mendorong batas standar menjadi semakin tinggi.',
            'blindSpot' => 'Tim sangat mudah gelisah dan sulit merasa puas. Kesuksesan kemarin cepat terasa usang, memicu kelelahan karena selalu mengejar target berikutnya.',
            'keyQuestion' => 'Apakah tim ini terus mengejar inovasi karena benar-benar ingin bertumbuh, atau karena takut tertinggal dan kalah pamor dari kompetitor?',
        ],
        'significance_contribution' => [
            'name' => 'The Purpose-Driven Achiever',
            'desire' => 'Tim ini ingin mencapai sesuatu yang monumental sekaligus memberikan dampak nyata dan besar bagi kehidupan banyak orang.',
            'fear' => 'Mencapai target finansial/bisnis tapi terasa hampa karena tidak membawa perubahan yang bermakna bagi lingkungan sekitar.',
            'strengths' => 'Tim bergerak dengan visi yang luar biasa jelas, menginspirasi pihak lain lewat hasil kerja nyata yang bukan sekadar angka atau teori.',
            'blindSpot' => 'Tim rentan mengalami tekanan besar untuk terus membuktikan bahwa karya mereka "berdampak". Validasi atas seberapa besar dampak mereka sering kali sulit terpuaskan.',
            'keyQuestion' => 'Apakah tim ini melakukan proyek besar demi tujuan sejatinya, atau demi dilihat sebagai tim pahlawan yang berdampak?',
        ],
        'connection_growth' => [
            'name' => 'The Growth Catalyst',
            'desire' => 'Tim ini percaya bahwa pertumbuhan dan pembelajaran terbaik selalu terjadi bersama-sama, bukan sendiri-sendiri.',
            'fear' => 'Terjebak dalam rutinitas kerja yang stagnan atau kehilangan semangat belajar bersama saat tekanan operasional meningkat.',
            'strengths' => 'Tim secara alami membangun lingkungan kerja yang saling mendorong, menikmati eksplorasi bersama, dan memfasilitasi orang lain untuk menyadari potensinya.',
            'blindSpot' => 'Tim bisa terlalu sibuk membantu anggota lain belajar atau bertumbuh, sampai lupa pada penyelesaian tugas inti atau mengeksekusi target jangka pendek secara disiplin.',
            'keyQuestion' => 'Apakah tim ini bertumbuh karena memang sudah saatnya, atau sekadar karena tidak tahan berdiam diri dalam stabilitas?',
        ],
        'connection_contribution' => [
            'name' => 'The Compassionate Builder',
            'desire' => 'Tim ini ingin membangun keharmonisan yang mendalam demi menciptakan produk, layanan, atau dukungan yang membuat hidup orang lain lebih baik.',
            'fear' => 'Tidak mampu memberi dukungan saat situasi krisis, atau terjebak dalam pekerjaan yang terasa dangkal dan transaksional murni.',
            'strengths' => 'Tim ini ibarat jangkar empati di organisasi. Mereka memberi dukungan tulus, menjaga hubungan jangka panjang, dan sangat bisa diandalkan secara emosional.',
            'blindSpot' => 'Tim terlalu sering menomorduakan kebutuhan atau batasan kerjanya sendiri demi membantu divisi/orang lain, yang berujung pada overwork dan rasa kelelahan diam-diam.',
            'keyQuestion' => 'Apakah tim ini selalu siap membantu karena kepedulian yang sehat, atau karena merasa bertanggung jawab atas kesuksesan semua orang?',
        ],
        'growth_contribution' => [
            'name' => 'The Transformational Builder',
            'desire' => 'Tim ini ingin terus berinovasi dan menggunakan pertumbuhan kompetensinya untuk menciptakan perubahan sistemik yang berarti bagi orang lain.',
            'fear' => 'Berhenti belajar dan kehilangan kapasitas untuk menciptakan terobosan atau nilai guna bagi masyarakat.',
            'strengths' => 'Tim berpikir jauh melampaui tren saat ini, cepat menerapkan wawasan baru menjadi solusi praktis, dan punya energi menular untuk mengubah status quo.',
            'blindSpot' => 'Tim mematok standar progres yang terlampau tinggi untuk organisasinya. Mereka rentan stres atau kecewa saat orang lain tidak beradaptasi secepat bayangan mereka.',
            'keyQuestion' => 'Apakah tim ini menggerakkan perubahan karena hal itu benar-benar krusial, atau sekadar karena tidak tahan melihat segala sesuatunya berjalan seperti biasa?',
        ],
    ]
];
